/* eslint-disable new-cap */
import {Inter} from 'next/font/google';
import './globals.css';
import { Metadata } from 'next';

const inter = Inter({subsets: ['latin']});
export const metadata: Metadata = {
	title: 'Next | Nome page',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
